#pragma once
#include "Header.hh"
//HACEMOS UN "FORWARD DECLARATION" DE LA CLASE MAPA, YA QUE NECESITAREMOS AL OBJETO MAPA PARA NUESTRO COIN MANAGER
//Y USAREMOS MÉTODOS DE LA CLASE MAPA PARA SABER EL CONTENIDO DE LAS CELDAS Y NO MATAR AL PLAYER O SUPERPONER MONEDAS
class Map;

class CoinManager
{
public:
	//CONSTRUCTOR DE MONEDAS EN FUNCIÓN DEL TAMAÑO DEL MAPA, TENDRÁ EN CUENTA EL NÚMERO DE CELDAS Y SUS LÍMITES
	CoinManager(Map &Map);

	//DESTRUCTOR DEL MAPA
	~CoinManager();

	//MÉTODO PARA LLENAR LAS CELDAS DEL MAPA CON UN DETERMINADO LOTE DE MONEDAS
	void refillCoins();

	//MÉTODO QUE GESTIONA EL CONTADOR DE MONEDAS
	void removeCoin();
	
private:
	//MI OBJETO MAPA DEL QUE ME VOY A SERVIR
	Map &myMap;

	//NÚMERO TOTAL DE MONEDAS QUE SE GENERARÁN EN EL REFILL (¡NO ES EL TOTAL DE MONEDAS DEL JUEGO!)
	int total_Coins;

	//COORDENADA X DE CADA MONEDA
	int x;

	//COORDENADA Y DE CADA MONEDA
	int y;

	//CHAR QUE REPRESENTA LA MONDA
	char coin{ '$' };

	//CHAR QUE REPRESENTA UNA CELDA VACÍA
	char emptyCell{ '.' };

	//CHAR QUE REPRESENTA AL PLAYER
	char playerChar{'@'};
};